---
apiVersion: v1
kind: Namespace
metadata:
  name: stateful-migration
  labels:
    app.kubernetes.io/name: stateful-migration
    app.kubernetes.io/part-of: stateful-migration-operator
    checkpoint-migration.dcn.io: "true" 